apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: sandbox-ingress

spec:
  ingressClassName: nginx

  rules:

    # Backend API
    - http:
        paths:

          - path: /api
            pathType: Prefix

            backend:
              service:
                name: sandbox-service
                port:
                  number: 80

          # Preview router
          - path: /preview
            pathType: Prefix

            backend:
              service:
                name: router-service
                port:
                  number: 80