apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: codespace-ingress

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:

    # Main API routes
    - http:
        paths:
          - path: /api/sandbox
            pathType: Prefix

            backend:
              service:
                name: sandbox-service

                port:
                  number: 80

    # Preview wildcard routes
    - host: "*.preview.localhost"

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: router-service

                port:
                  number: 80